on: push
name: Deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: pnpm/action-setup@v4

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Sync
        run: |
          sudo apt-get install sshpass
          rsync --stats --delete -rpot --rsh="sshpass -p ${{ secrets.HOST_PASS }} ssh -o StrictHostKeyChecking=no -l ${{ secrets.HOST_USER }}" dist/ ${{ secrets.HOST_PATH }}
